[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.2",
    "langchain>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.7",
    "langsmith>=0.14.4",
    "openai>=3.24.0",
    "python-dotenv>=1.2.4",
]
